[package]
name = "day01"
version = "0.1.0"
edition = "2021"

[lib]
bench = false
doctest = false

[[bin]]
name = "day01"
bench = false
test = false

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "benchmark"
harness = false
