use crate::common::Grid;

pub fn run(input: &str) -> usize {
    let mut grid: Grid = input.parse().unwrap();

    let mut round = 0;
    while !grid.simulate(round) {
        round += 1;
    }

    round + 1
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn examples() {
        let example = "..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
..............";

        assert_eq!(run(example), 20);
    }
}
