name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release
      - name: Run clippy
        run: cargo clippy --release
      - name: Run benchmark
        run: cargo bench --workspace --exclude template -- --quiet --quick
